name: CD | Check pull request

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - '**/*.txt'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-22.04", "ubuntu-24.04", "windows-2022", "macos-14" ]
        node-version: [ "22.x", "24.x" ]
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false
      - run: npm install

      - name: Compile
        run: npm run compile --if-present
      - name: Run tests & produce junit
        run: npm run test:ci

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #v5.0.0
        with:
          name: mocha-results-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.node-version }}
          path: |
            mocha-report.xml
            test-results.xml
          retention-days: 7
